### ISSUE TITLE
ProjectsManagerActor likes to blow up things

### ISSUE THREAD

**Issue by CSchoel** [THM-MoTE/mope-server#9]
When I try to connect to a Mo|E server version 0.6.5 with the Atom plugin I get an error that says `Couldn't initialize a new ProjectManager - blow up system`.

This happened with an Oracle JDK 11.

Here is the content of the log file:

```
2019-02-27 15:39:10,382 [INFO ] a.e.s.Slf4jLogger [] - Slf4jLogger started
2019-02-27 15:39:10,382 [INFO ] a.e.s.Slf4jLogger [] - Slf4jLogger started
2019-02-27 15:39:10,464 [DEBUG] d.t.m.s.ProjectsManagerActor [akka://moie-system
/user/projects-manager] - starting
2019-02-27 15:39:10,470 [INFO ] d.t.m.s.RecentFilesActor [akka://moie-system/use
r/projects-manager/rf] - Initialized with file C:\Users\CSchoel\.config\mope\rec
ent-files.json
2019-02-27 15:39:10,474 [DEBUG] d.t.m.s.RecentFilesActor [akka://moie-system/use
r/projects-manager/rf] - Recent files are List()
2019-02-27 15:39:10,513 [INFO ] d.t.m.s.Server [Server(akka://moie-system)] - Mo
PE-server - Version: 0.6.5 - Development
2019-02-27 15:39:11,867 [INFO ] d.t.m.s.Server [Server(akka://moie-system)] - Se
rver running at localhost:9001
2019-02-27 15:39:22,897 [INFO ] d.t.m.s.ProjectsManagerActor [akka://moie-system
/user/projects-manager] - new manager for id:0
2019-02-27 15:39:22,897 [INFO ] d.t.m.c.OMCompiler [] - No libraries given
2019-02-27 15:39:22,905 [INFO ] omc.OmcExecuter [] - started [D:\Software\OpenMo
delica1.13.0-dev-64bit\bin\omc.exe, --interactive=zmq, -z=mope_local] en_US.UTF-
8 - locale C:\Users\CSchoel\AppData\Local\Temp\omc_home\omc.log - output redirec
ting to: {}
2019-02-27 15:39:25,966 [ERROR] d.t.m.s.ProjectsManagerActor [akka://moie-system
/user/projects-manager] - Couldn't initialize a new ProjectManager - blow up sys
tem
2019-02-27 15:39:25,980 [ERROR] a.a.OneForOneStrategy [akka://moie-system/user/p
rojects-manager] - null
java.lang.reflect.InvocationTargetException: null
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInsta
nce0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInsta
nce(NativeConstructorAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newI
nstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:
490) ~[na:na]
        at de.thm.mope.compiler.CompilerFactory.newCompiler(CompilerFactory.scal
a:37) ~[mope-server-0.6.5.jar:0.6.5]
        at de.thm.mope.MopeModule.$anonfun$projManagerFactory$1(MopeModule.scala
:75) ~[mope-server-0.6.5.jar:0.6.5]
        at de.thm.mope.MopeModule.$anonfun$projManagerFactory$1$adapted(MopeModu
le.scala:74) ~[mope-server-0.6.5.jar:0.6.5]
        at de.thm.mope.server.ProjectsManagerActor.de$thm$mope$server$ProjectsMa
nagerActor$$newManager(ProjectsManagerActor.scala:46) ~[mope-server-0.6.5.jar:0.
6.5]
        at de.thm.mope.server.ProjectsManagerActor$$anonfun$receive$1.$anonfun$a
pplyOrElse$1(ProjectsManagerActor.scala:59) ~[mope-server-0.6.5.jar:0.6.5]
        at de.thm.mope.server.ProjectsManagerActor$$anonfun$receive$1.$anonfun$a
pplyOrElse$1$adapted(ProjectsManagerActor.scala:59) ~[mope-server-0.6.5.jar:0.6.
5]
        at de.thm.mope.server.ProjectRegister.$anonfun$add$2(ProjectRegister.sca
la:62) ~[mope-server-0.6.5.jar:0.6.5]
        at scala.runtime.java8.JFunction1$mcII$sp.apply(JFunction1$mcII$sp.java:
23) ~[mope-server-0.6.5.jar:0.6.5]
        at de.thm.mope.server.ProjectRegister.withNewId(ProjectRegister.scala:38
) ~[mope-server-0.6.5.jar:0.6.5]
        at de.thm.mope.server.ProjectRegister.add(ProjectRegister.scala:61) ~[mo
pe-server-0.6.5.jar:0.6.5]
        at de.thm.mope.server.ProjectsManagerActor$$anonfun$receive$1.applyOrEls
e(ProjectsManagerActor.scala:59) ~[mope-server-0.6.5.jar:0.6.5]
        at akka.actor.Actor.aroundReceive(Actor.scala:502) ~[mope-server-0.6.5.j
ar:0.6.5]
        at akka.actor.Actor.aroundReceive$(Actor.scala:500) ~[mope-server-0.6.5.
jar:0.6.5]
        at de.thm.mope.server.ProjectsManagerActor.aroundReceive(ProjectsManager
Actor.scala:27) ~[mope-server-0.6.5.jar:0.6.5]
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526) ~[mope-serve
r-0.6.5.jar:0.6.5]
        at akka.actor.ActorCell.invoke(ActorCell.scala:495) ~[mope-server-0.6.5.
jar:0.6.5]
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) ~[mope-server
-0.6.5.jar:0.6.5]
        at akka.dispatch.Mailbox.run(Mailbox.scala:224) ~[mope-server-0.6.5.jar:
0.6.5]
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234) ~[mope-server-0.6.5.jar
:0.6.5]
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:
290) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Fo
rkJoinPool.java:1020) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:16
56) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.ja
va:1594) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorke
rThread.java:177) ~[na:na]
Caused by: java.nio.file.NoSuchFileException: C:\Users\CSchoel\AppData\Local\Tem
p\openmodelica.CSchoel.port.mope_local
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsE
xception.java:85) ~[na:na]
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsExc
eption.java:103) ~[na:na]
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsExc
eption.java:108) ~[na:na]
        at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(Windows
FileSystemProvider.java:231) ~[na:na]
        at java.base/java.nio.file.Files.newByteChannel(Files.java:370) ~[na:na]

        at java.base/java.nio.file.Files.newByteChannel(Files.java:421) ~[na:na]

        at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSys
temProvider.java:420) ~[na:na]
        at java.base/java.nio.file.Files.newInputStream(Files.java:155) ~[na:na]

        at java.base/java.nio.file.Files.newBufferedReader(Files.java:2838) ~[na
:na]
        at java.base/java.nio.file.Files.readAllLines(Files.java:3327) ~[na:na]
        at omc.ZeroMQClient.readPortFile(ZeroMQClient.java:124) ~[mope-server-0.
6.5.jar:0.6.5]
        at omc.ZeroMQClient.connect(ZeroMQClient.java:105) ~[mope-server-0.6.5.j
ar:0.6.5]
        at de.thm.mope.compiler.OMCompiler.<init>(OMCompiler.scala:58) ~[mope-se
rver-0.6.5.jar:0.6.5]
        ... 28 common frames omitted
```

**Comment by njustus** [comment]
Hmpf interesting.. so OpenModelica dumps the port file to somewhere else than on Linux systems ..

The problem is this part of the error:
```
Caused by: java.nio.file.NoSuchFileException: C:\Users\CSchoel\AppData\Local\Temp\openmodelica.CSchoel.port.mope_local
```

To fix this i need to know, where OpenModelica dumps the port  file on Windows systems?? This is usually reported in the OMC log file at: `$TMP/omc_home/omc.log`.
May be we should parse the output of OMC, it always looks like this :thinking: :
```
Created ZeroMQ Server.
Dumped server port in file: /tmp/openmodelica.nico.port.mope_local%                                                     
```
